### PR TITLE
Update homely.install to support pacman

### PR DESCRIPTION
**Pull request by Darksider3**
adding pacman to the supported package managers for arch support.

### CODE REVIEW

**Comment by phodge** [comment]
Hi @Darksider3 ! Thanks so much for the PR. I can't merge it without also adding something to the docs that homely will also attempt to install things via pacman (the current behaviour is to try every single package manager from `_METHODS` that's installed).

If you can update the docs to mention `pacman` as being one of the supported package managers then that should be all I need to merge your branch. Otherwise I will try and get to it myself when I can.

**Comment by Darksider3** [comment]
Hey, 
Ah, the docs. I thought about that while creating that PR, but forgot to ask, sorry. 
Of course, i'll update the docs. Should i just update the docs/ref/install.rst or every document that mentions specific package managers? (Like, slides.rst as well as the tutorial.rst?)
Thanks for the quick response!

**Comment by phodge** [comment]
Hi! Sorry to be pedantic but I think that `tutorial.rst` will need to be updated as well, otherwise it will be misleading to new users. But don't worry about `slides.rst`, that was just used for my live presentation at BrisPy back in 2017.

**Comment by Darksider3** [comment]
Hey,
Nah, you aren't pedantic IMO, you're careful. :) Will update the `tutorial.rst`  tomorrow as early as possible! :+1:

**Comment by Darksider3** [comment]
Sorry, i somehow missed to add the tutorial.rst o_o Had to `--amend`.

**Pull request merged**
